#!/usr/bin/env /bin/bash

set -e

DEFAULT_TASK="install"

if [[ -z $@ ]]
then
    echo -e "empty task param, run default ${DEFAULT_TASK} task"
    TASK=$DEFAULT_TASK
else
    TASK=$@
fi

echo -e "running $TASK task"

docker exec -it ${PROJECT_NAME}_node /bin/bash -c "\
umask g=rwx,u=rwx,o=rwx &&\
cd /var/www/.bundler &&\
npm $TASK"

