#!/usr/bin/env /bin/bash

VERSION="1.0.2"
DCMD_STOP_TIMEOUT="3"
VERSION_FLAGS=("-v" "--version" "version")
LIST_FLAGS=("-l" "--list" "ls")
HELP_FLAGS=("help" "--help")

if [[ -z "$DOCKER_FOLDER" ]]; then
  DOCKER_FOLDER=$(pwd)/.docker
fi

set -e

if [[ -f $DOCKER_FOLDER/.env ]]; then
  export $(grep -v '^#' $DOCKER_FOLDER/.env | xargs)
else
  echo -e "\n"
  echo -e "⚠️  Your .docker/.env file does not exist"
  echo -e "\n"
  exit 1;
fi

if [[ ! -d $DOCKER_FOLDER ]]; then

  echo -e "\n"
  echo -e "⚠️  You're not at root of your docker folder, no .docker has been found"
  echo -e "\n"
  exit 1;

fi

if [[ "$1" == "up" ]]; then

  shift;
  docker compose -f $DOCKER_FOLDER/docker-compose.yml up --build -d $@

elif [[ "$1" == "down" ]]; then

  shift;
  docker compose -f $DOCKER_FOLDER/docker-compose.yml down -v -t $DCMD_STOP_TIMEOUT $@

elif [[ "$1" == "stop" ]]; then

  shift;
  docker compose -f $DOCKER_FOLDER/docker-compose.yml stop -t $DCMD_STOP_TIMEOUT $@

elif [[ "$1" == "start" ]]; then

  shift;
  docker compose -f $DOCKER_FOLDER/docker-compose.yml start $@

elif [[ "$1" == "restart" ]]; then

  shift;
  docker compose -f $DOCKER_FOLDER/docker-compose.yml restart -t $DCMD_STOP_TIMEOUT $@

elif [[ "$1" == "update" ]]; then

  echo -e "Updating dcmd..."

  DCMD_PATH=$(which dcmd)
  CONTENT=$(curl -s https://raw.githubusercontent.com/PaulWeinsberg/dcmd/main/dcmd)

  echo "$CONTENT" | sudo tee $DCMD_PATH > /dev/null
  echo -e "DCMD updated to version $VERSION in the path $DCMD_PATH"

elif [[ ${VERSION_FLAGS[*]} =~ "$1" ]]; then

  echo -e "Docker Commands v${VERSION}"

elif [[ ${HELP_FLAGS[*]} =~ "$1" ]] || [[ -z "$@" ]]; then

  echo -e "Docker Commands v${VERSION}"
  echo -e "Run dcmd ls to see all available commands"

elif [[ ${LIST_FLAGS[*]} =~ "$1" ]]; then

  echo -e "Available built-in commands:"
  echo -e "\n"
  echo -e "dcmd up"
  echo -e "dcmd down"
  echo -e "dcmd stop"
  echo -e "dcmd start"
  echo -e "dcmd restart"
  echo -e "dcmd update"
  echo -e "dcmd version"
  echo -e "dcmd help"
  echo -e "dcmd ls"

  echo -e "\n"

  echo -e "Available custom commands:"
  echo -e "\n"

  for APP in $(ls $DOCKER_FOLDER/commands); do
    APP_COMMAND_PATH=$DOCKER_FOLDER/commands/$APP
    if [[ -d $APP_COMMAND_PATH ]]; then
      for APP_COMMAND in $(ls $APP_COMMAND_PATH); do
        echo -e "dcmd $APP $APP_COMMAND"
      done
    else
      echo -e "dcmd $APP"
    fi
  done

elif [[ -d $DOCKER_FOLDER/commands/$1 ]]; then

  COMMAND=$DOCKER_FOLDER/commands/$1/$2
  shift; shift;
  PARAMS="$@"
  IS_COMMAND=1

else

  COMMAND=$DOCKER_FOLDER/commands/$1
  shift;
  PARAMS="$@"
  IS_COMMAND=1

fi

if [[ $IS_COMMAND ]]; then

  if [[ ! -f $COMMAND ]]; then
    echo -e "\n"
    echo -e "⚠️  The command $COMMAND does not exists"
    echo -e "\n"
    exit 1;

  else

    source $COMMAND

  fi

fi

