#!env /bin/bash

set -e

cargo build --release --target aarch64-apple-darwin
cargo build --release --target x86_64-apple-darwin
cargo build --release --target aarch64-unknown-linux-gnu
cargo build --release --target x86_64-unknown-linux-gnu

cp target/aarch64-apple-darwin/release/dcmd bin/aarch64-apple-darwin/dcmd
cp target/x86_64-apple-darwin/release/dcmd bin/x86_64-apple-darwin/dcmd
cp target/aarch64-unknown-linux-gnu/release/dcmd bin/aarch64-unknown-linux-gnu/dcmd
cp target/x86_64-unknown-linux-gnu/release/dcmd bin/x86_64-unknown-linux-gnu/dcmd