[package]
name = "dcmd"
version = "1.0.7"
edition = "2021"

[profile.release]
strip = "debuginfo"

[dependencies]
envmnt = "0.10.4"
indexmap = "1.9.3"
serde = { version = "1.0.159", features = ["derive"] }
toml = "0.7.3"
