[package]
name = "dcmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envmnt = "0.10.4"
indexmap = "1.9.3"
