#!/usr/bin/env /bin/bash

set -e

docker exec -i ${PROJECT_NAME}_db /bin/bash -c "mysqldump -u root -proot default --max_allowed_packet=512M" > "${PROJECT_ROOT}/.docker/backup/db.sql"
rsync -avhP "${PROJECT_ROOT}/web/sites/default/files/" "${PROJECT_ROOT}/.docker/backup/files/"

cd "${PROJECT_ROOT}/.docker/backup"

rm -rf backup.tar.gz
tar -czvf backup.tar.gz .

cd -

echo -e "📦 Backup successfully created"
