#!/usr/bin/env /bin/bash

set -e

echo -e "Importing database..."
docker exec -i ${PROJECT_NAME}_db mysql -u root -proot default < ${PROJECT_ROOT}/.docker/backup/db.sql

echo -e "Importing files..."
rsync -avhP "${PROJECT_ROOT}/.docker/backup/files/" "${PROJECT_ROOT}/web/sites/default/files/"

echo -e "✅ Database and files restored"


